defaults:
    - _self_
    - transforms: sibyl
    - features: amr

working_dir: "./fada/fadata"
dataset_dir: "${working_dir}/datasets"
results_dir: "./eval/results"

amr_extractor:
    amr_dir: "${working_dir}/amrs"
    amr_save_path: "${amr_extractor.amr_dir}/${dataset.builder_name}.${dataset.config_name}.pkl"
    max_sent_len: 64
    batch_size: 8

alignment_extractor:
    model_id: "distilbert-base-uncased-finetuned-sst-2-english"

dataset:
    builder_name: "glue"
    config_name: "sst2"
    text_key: "text"
    task_name: "sentiment"
    num_per_class: "infer" # 10, 200, 2500, "min", "infer"
    max_size: 100000

fada: 
    tfim_dir: "${working_dir}/tfim"
    min_coverage: 128
    num_to_transform_per_step: 128
    max_iterations: 8
    c_a: 0.8
    c_f: 0.1
    c_g: 0.1
    force: False

augment:
    technique: "all" # uniform, fada, fada-sweep, all, transfer
    num_transforms_to_apply: 1
    num_augmentations_per_record: 3
    batch_size: 8
    keep_originals: True
    tfim_dataset_builder_name: "${dataset.builder_name}"
    tfim_dataset_config_name: "${dataset.config_name}"
    save_dir: "${dataset_dir}"
    force: False

train:
    num_runs: 1
    dataset_matcher: "${dataset.builder_name}.${dataset.config_name}.*"
    base_models: 
        - "prajjwal1/bert-tiny"
        - "bert-base-uncased"
    num_epochs: 10
    logging_steps_per_epoch: 10
    early_stopping_patience: 10
    gradient_accumulation_steps: 1
    train_batch_size: 2
    eval_batch_size: 16
    learning_rate: 2e-5
    weight_decay: 0.01
    visible_cuda_devices: "0,1"
    max_val_size: 250
    trained_models_dir: "./eval/pretrained"
    save_path: "${results_dir}/${dataset.builder_name}.${dataset.config_name}.training.csv"

robustness:
    num_runs: 1
    model_matcher: "${train.trained_models_dir}/*${dataset.builder_name}.${dataset.config_name}.*"
    num_advs: 100
    visible_cuda_devices: "0,1"
    attacks: 
        # - textattack.attack_recipes.BERTAttackLi2020 # 120 min / 100 examples
        - textattack.attack_recipes.CheckList2020 # 15 min / 100 examples
        - textattack.attack_recipes.DeepWordBugGao2018 # 15 min / 100 examples
        - textattack.attack_recipes.TextBuggerLi2018 # 15 min / 100 examples
        - textattack.attack_recipes.TextFoolerJin2019 # 15 min / 100 examples
    save_path: "${results_dir}/${dataset.builder_name}.${dataset.config_name}.robustness.csv"

quality:
    dataset_matcher: "${dataset.builder_name}.${dataset.config_name}.*"
    model_id: "${alignment_extractor.model_id}"
    max_dataset_size: 1000
    save_path: "${results_dir}/${dataset.builder_name}.${dataset.config_name}.quality.csv"